# LightVoting Default Config

variables:
  runs: '1'
  configs: '1'
  grouping: RANDOM
  protocol: ITERATIVE
  altnum: '6'

# TODO set other parameters here -> capacity, diss threshold, join threshold
